# program to show the use of Bitwise operator
print("Enter the value or operand-1: ")
p=int(input())
print("Enter the value or operand-2: ")
q=int(input())
print("Entered value or operand-1 is : ",p)
print("Entered value or operand-2 is : ",q)
print("AND:", (p&q))
print("OR:", p|q)
print("XOR:", p^q)
print("complement of p:", ~p)
print("complement of q:", ~q)
print("Shift Right of p:", p<<2)
print("Shift Right of q:", p<<2)
print("Shift Left of p:", p>>2)
print("Shift Left of q:", q>>2)