# Program to perform Airthematic Operation for understanding
print("Enter the value or operand-1: ")
p=int(input())
print("Enter the value or operand-2: ")
q=int(input())
print("Entered value or operand-1 is : ",p)
print("Entered value or operand-2 is : ",q)
r= input()
print("\n\n\n Addition of Both operands is:",(p+q))
print("\n\n\n Subtraction of Both operands is:",(p-q))
print("\n\n\n Multiplication of Both operands is:",(p*q))
print("\n\n\n Division of Both operands is:",(p/q))
print("\n\n\n Modular of Both operands is:",(p%q))
print("\n\n\n Exponent of Both operands is:",(p**q))
print("\n\n\n Floor Division of Both operands is:",(p//q))